installer:
  release: "v0.4.28"
  image: "quay.io/devtron/inception"
  tag: "c62d4c30-185-9354"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:607f522d-325-9604"
  devtron:
    image: "quay.io/devtron/hyperion:72e36aff-280-9764"
    cicdImage: "quay.io/devtron/devtron:8d117f35-326-9868"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:415f5470-279-6520"
      cicdAuthenticator: "quay.io/argoproj/argocd:v1.8.1"
  kubelink:
    image: "quay.io/devtron/kubelink:59a0df88-318-9226"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "8d117f35618c9f4dbdefec671db53a98c00106dc"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "8d117f35618c9f4dbdefec671db53a98c00106dc"
